ex0: ex0.c
	gcc -g -Wall ex0.c -o ex0

ex1: ex1.c
	gcc -g -Wall ex1.c -o ex1

ex2: ex2.c
	gcc -g -Wall ex2.c -o ex2

ex3: ex3.c
	gcc -g -Wall ex3.c -o ex3

ex4: ex4.c
	gcc -g -Wall ex4.c -o ex4

ex5: ex5.c
	gcc -g -Wall ex5.c -o ex5

ex6: ex6.c
	gcc -g -Wall ex6.c -o ex6

ex7: ex7.c
	gcc -g -Wall ex7.c -o ex7

ex8: ex8.c
	gcc -g -Wall ex8.c -o ex8

ex9: ex9.c
	gcc -g -Wall ex9.c -o ex9

ex10: ex10.c
	gcc -g -Wall ex10.c -o ex10

ex11: ex11.c
	gcc -g -Wall ex11.c -o ex11

ex12: ex12.c
	gcc -g -Wall ex12.c -o ex12

ex13: ex13.c
	gcc -g -Wall ex13.c -o ex13

ex14: ex14.c
	gcc -g -Wall ex14.c -o ex14

ex15: ex15.c
	gcc -g -Wall ex15.c -o ex15

ex16: ex16.c
	gcc -g -Wall ex16.c -o ex16

ex17: ex17.c
	gcc -g -Wall ex17.c -o ex17

ex18: ex18.c
	gcc -g -Wall ex18.c -o ex18

ex19: ex19.c
	gcc -g -Wall ex19.c -o ex19

ex20: ex20.c
	gcc -g -Wall ex20.c -o ex20

ex21: ex21.c
	gcc -g -Wall ex21.c -o ex21

ex22: ex22.c
	gcc -g -Wall ex22.c -o ex22

ex23: ex23.c
	gcc -g -Wall ex23.c -o ex23

ex24: ex24.c
	gcc -g -Wall ex24.c -o ex24

ex25: ex25.c
	gcc -g -Wall ex25.c -o ex25

ex26: ex26.c
	gcc -g -Wall ex26.c -o ex26

ex27: ex27.c
	gcc -g -Wall ex27.c -o ex27

ex28: ex28.c
	gcc -g -Wall ex28.c -o ex28

ex29: ex29.c
	gcc -g -Wall ex29.c -o ex29

ex30: ex30.c
	gcc -g -Wall ex30.c -o ex30

ex31: ex31.c
	gcc -g -Wall ex31.c -o ex31

ex32: ex32.c
	gcc -g -Wall ex32.c -o ex32

ex33: ex33.c
	gcc -g -Wall ex33.c -o ex33

ex34: ex34.c
	gcc -g -Wall ex34.c -o ex34

ex35: ex35.c
	gcc -g -Wall ex35.c -o ex35

ex36: ex36.c
	gcc -g -Wall ex36.c -o ex36

ex37: ex37.c
	gcc -g -Wall ex37.c -o ex37

ex38: ex38.c
	gcc -g -Wall ex38.c -o ex38

ex39: ex39.c
	gcc -g -Wall ex39.c -o ex39

ex40: ex40.c
	gcc -g -Wall ex40.c -o ex40

ex41: ex41.c
	gcc -g -Wall ex41.c -o ex41

ex42: ex42.c
	gcc -g -Wall ex42.c -o ex42

ex43: ex43.c
	gcc -g -Wall ex43.c -o ex43

ex44: ex44.c
	gcc -g -Wall ex44.c -o ex44

ex45: ex45.c
	gcc -g -Wall ex45.c -o ex45

ex46: ex46.c
	gcc -g -Wall ex46.c -o ex46

ex47: ex47.c
	gcc -g -Wall ex47.c -o ex47
